# Generated by Django 4.1.7 on 2023-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=600)),
                ('content', models.TextField(max_length=6000)),
                ('date_post', models.DateTimeField()),
                ('date_ini', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=600)),
                ('link', models.URLField()),
                ('date_post', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=600)),
                ('file', models.FileField(upload_to='')),
                ('date_post', models.DateTimeField()),
            ],
        ),
    ]
